export declare const enum PngChunkType {
    IHDR = "IHDR",
    cHRM = "cHRM",
    gAMA = "gAMA",
    sBIT = "sBIT",
    PLTE = "PLTE",
    bKGD = "bKGD",
    hIST = "hIST",
    tRNS = "tRNS",
    oFFs = "oFFs",
    pHYs = "pHYs",
    sCAL = "sCAL",
    IDAT = "IDAT",
    tIME = "tIME",
    tEXt = "tEXt",
    zTXt = "zTXt",
    fRAc = "fRAc",
    gIFg = "gIFg",
    gIFt = "gIFt",
    gIFx = "gIFx",
    IEND = "IEND"
}
