export declare const enum FlacChmode {
    FLAC_CHMODE_INDEPENDENT = 0,
    FLAC_CHMODE_LEFT_SIDE = 1,
    FLAC_CHMODE_RIGHT_SIDE = 2,
    FLAC_CHMODE_MID_SIDE = 3
}
export declare const enum FlacMetadataType {
    FLAC_METADATA_TYPE_STREAMINFO = 0,
    FLAC_METADATA_TYPE_PADDING = 1,
    FLAC_METADATA_TYPE_APPLICATION = 2,
    FLAC_METADATA_TYPE_SEEKTABLE = 3,
    FLAC_METADATA_TYPE_VORBIS_COMMENT = 4,
    FLAC_METADATA_TYPE_CUESHEET = 5,
    FLAC_METADATA_TYPE_PICTURE = 6,
    FLAC_METADATA_TYPE_INVALID = 127
}
