import { AVCodecID } from 'avutil/codec';
export declare const WavTag2CodecId: {
    1: AVCodecID;
    2: AVCodecID;
    3: AVCodecID;
    6: AVCodecID;
    7: AVCodecID;
    10: AVCodecID;
    16: AVCodecID;
    17: AVCodecID;
    23: AVCodecID;
    32: AVCodecID;
    34: AVCodecID;
    49: AVCodecID;
    50: AVCodecID;
    56: AVCodecID;
    66: AVCodecID;
    69: AVCodecID;
    20: AVCodecID;
    64: AVCodecID;
    97: AVCodecID;
    98: AVCodecID;
    100: AVCodecID;
    105: AVCodecID;
    117: AVCodecID;
    131: AVCodecID;
    255: AVCodecID;
    273: AVCodecID;
    5632: AVCodecID;
    5634: AVCodecID;
    8192: AVCodecID;
};
export declare const codecBmpTags: Record<int32, AVCodecID>;
