import Matrix3 from 'common/math/Matrix3';
export declare const Rec709: number[];
export declare const Rec470SystemM: number[];
export declare const Rec470SystemBG: number[];
export declare const Rec601: number[];
export declare const SMPTE_ST_240: number[];
export declare const GenericFilm: number[];
export declare const Rec2020: number[];
export declare const SMPTE_ST_428_1: number[];
export declare const SMPTE_RP_431_2: number[];
export declare const SMPTE_EG_432_1: number[];
export declare const ITU_T_H273_VALUE22: number[];
export declare const SRGB: number[];
export declare const P3: number[];
export declare const A98RGB: number[];
export declare const ProPhotoRGB: number[];
export declare const XYZD50: number[];
export declare const XYZD65: number[];
export declare const Invalid: number[];
export declare const AppleGenericRGB: number[];
export declare const WideGamutColorSpin: number[];
export declare function primariesToXYZD50(pri: float[]): Matrix3;
