import { BytesWriterSync } from 'common/io/interface';
import { EBMLId } from './matroska';
import IOWriterSync from 'common/io/IOWriterSync';
import { Attachment, Attachments, AudioTrack, Chapter, ChapterAtom, ChapterDisplay, Chapters, CuePoint, CuePointPos, Cues, Header, Info, OMatroskaContext, SeekHead, SeekHeadEntry, SimpleTag, Tag, TagTargets, Tags, TrackEntry, Tracks, VideoColor, VideoTrack } from './type';
export declare function ebmlIdSize(id: EBMLId): number;
export declare function ebmlNumSize(value: number | bigint): number;
export declare function ebmlLengthSize(value: number | bigint): number;
export declare function writeEbmlNum(writer: BytesWriterSync, value: number | bigint, bytes: int32): void;
export declare function writeEbmlId(writer: BytesWriterSync, id: EBMLId): void;
export declare function writeEbmlLength(writer: BytesWriterSync, length: number | bigint, bytes?: int32): void;
export declare function writeEbmlLengthUnknown(writer: BytesWriterSync, bytes: int32): void;
export declare function writeEbmlUid(writer: IOWriterSync, id: EBMLId, uid: uint64): void;
export declare function writeEbmlUint(writer: IOWriterSync, id: EBMLId, value: number | bigint): void;
export declare function writeEbmlFloat(writer: IOWriterSync, id: EBMLId, value: float): void;
export declare function writeEbmlDouble(writer: IOWriterSync, id: EBMLId, value: double): void;
export declare function writeEbmlBuffer(writer: IOWriterSync, id: EBMLId, value: Uint8Array): void;
export declare function writeEbmlString(writer: IOWriterSync, id: EBMLId, value: string): void;
export declare function writeEbmlVoid(writer: IOWriterSync, size: int32): void;
export declare function updatePositionSize(ioWriter: IOWriterSync, context: OMatroskaContext): void;
export declare function writeEleData(writer: IOWriterSync, context: OMatroskaContext, id: EBMLId, data: (eleWriter: IOWriterSync) => void): void;
export declare function writeHeader(writer: IOWriterSync, context: OMatroskaContext, header: Header): void;
export declare function writeSeekHeaderEntry(writer: IOWriterSync, context: OMatroskaContext, entry: SeekHeadEntry): void;
export declare function writeSeekHeader(writer: IOWriterSync, context: OMatroskaContext, header: SeekHead): void;
export declare function writeInfo(writer: IOWriterSync, context: OMatroskaContext, info: Info): void;
export declare function writeVideoColor(writer: IOWriterSync, context: OMatroskaContext, color: VideoColor): void;
export declare function writeVideoTrack(writer: IOWriterSync, context: OMatroskaContext, video: VideoTrack): void;
export declare function writeAudioTrack(writer: IOWriterSync, context: OMatroskaContext, audio: AudioTrack): void;
export declare function writeTrack(writer: IOWriterSync, context: OMatroskaContext, track: TrackEntry): void;
export declare function writeTracks(writer: IOWriterSync, context: OMatroskaContext, tracks: Tracks): void;
export declare function writeTagTag(writer: IOWriterSync, context: OMatroskaContext, tag: SimpleTag): void;
export declare function writeTagTarget(writer: IOWriterSync, context: OMatroskaContext, target: TagTargets): void;
export declare function writeTag(writer: IOWriterSync, context: OMatroskaContext, tag: Tag): void;
export declare function writeTags(writer: IOWriterSync, context: OMatroskaContext, tags: Tags): void;
export declare function writeCuePosition(writer: IOWriterSync, context: OMatroskaContext, pos: CuePointPos): void;
export declare function writeCue(writer: IOWriterSync, context: OMatroskaContext, cue: CuePoint): void;
export declare function writeCues(writer: IOWriterSync, context: OMatroskaContext, cues: Cues): void;
export declare function writeChapterAtomDisplay(writer: IOWriterSync, context: OMatroskaContext, display: ChapterDisplay): void;
export declare function writeChapterAtom(writer: IOWriterSync, context: OMatroskaContext, atom: ChapterAtom): void;
export declare function writeChapter(writer: IOWriterSync, context: OMatroskaContext, chapter: Chapter): void;
export declare function writeChapters(writer: IOWriterSync, context: OMatroskaContext, chapters: Chapters): void;
export declare function writeAttachment(writer: IOWriterSync, context: OMatroskaContext, attachment: Attachment): void;
export declare function writeAttachments(writer: IOWriterSync, context: OMatroskaContext, attachments: Attachments): void;
