import AVPacket, { AVPacketSideData } from '../struct/avpacket';
import { AVPacketSideDataType } from '../codec';
import SafeUint8Array from 'cheap/std/buffer/SafeUint8Array';
export declare function getAVPacketData(avpacket: pointer<AVPacket>): Uint8Array;
export declare function getAVPacketData(avpacket: pointer<AVPacket>, safe: boolean): SafeUint8Array;
export declare function initAVPacketData(avpacket: pointer<AVPacket>, length: size): Uint8Array;
export declare function getAVPacketSideData(avpacket: pointer<AVPacket>, type: AVPacketSideDataType): pointer<AVPacketSideData>;
export declare function hasAVPacketSideData(avpacket: pointer<AVPacket>, type: AVPacketSideDataType): boolean;
export declare function addSideData(psd: pointer<pointer<AVPacketSideData>>, pnbSd: pointer<int32>, type: AVPacketSideDataType, data: pointer<void>, length: size): pointer<AVPacketSideData>;
export declare function newSideData(psd: pointer<pointer<AVPacketSideData>>, pnbSd: pointer<int32>, type: AVPacketSideDataType, size: size): pointer<AVPacketSideData>;
export declare function addAVPacketSideData(avpacket: pointer<AVPacket>, type: AVPacketSideDataType, data: pointer<void>, length: size): void;
export declare function deleteAVPacketSideData(avpacket: pointer<AVPacket>, type: AVPacketSideDataType): void;
export declare function createAVPacket(): pointer<AVPacket>;
export declare function destroyAVPacket(avpacket: pointer<AVPacket>): void;
export declare function freeAVPacketSideData(pSideData: pointer<pointer<AVPacketSideData>>, pnbSideData: pointer<int32>): void;
export declare function getAVPacketDefault(avpacket: pointer<AVPacket>): void;
export declare function copyAVPacketSideData(dst: pointer<AVPacket>, src: pointer<AVPacket>): void;
export declare function copyAVPacketProps(dst: pointer<AVPacket>, src: pointer<AVPacket>): number;
export declare function refAVPacket(dst: pointer<AVPacket>, src: pointer<AVPacket>): number;
export declare function unrefAVPacket(avpacket: pointer<AVPacket>): void;
export declare function copyAVPacketData(dst: pointer<AVPacket>, src: pointer<AVPacket>): void;
export declare function addAVPacketData(avpacket: pointer<AVPacket>, data: pointer<uint8>, size: size): void;
