export declare function r8(p: pointer<void>): uint8;
export declare function rl16(p: pointer<void>): uint16;
export declare function rb16(p: pointer<void>): uint16;
export declare function rl24(p: pointer<void>): int32;
export declare function rb24(p: pointer<void>): int32;
export declare function rl32(p: pointer<void>): int32;
export declare function rb32(p: pointer<void>): int32;
export declare function rl64(p: pointer<void>): int64;
export declare function rb64(p: pointer<void>): int64;
