export declare function w8(p: pointer<void>, value: number): void;
export declare function wl16(p: pointer<void>, value: uint16): void;
export declare function wb16(p: pointer<void>, value: uint16): void;
export declare function wl24(p: pointer<void>, value: uint32): void;
export declare function wb24(p: pointer<void>, value: uint32): void;
export declare function wl32(p: pointer<void>, value: uint32): void;
export declare function wb32(p: pointer<void>, value: uint32): void;
export declare function wl64(p: pointer<void>, value: uint64): void;
export declare function wb64(p: pointer<void>, value: uint64): void;
