export declare const enum BoxType {
    MDAT = "mdat",
    IDAT = "idat",
    FREE = "free",
    WIDE = "wide",
    SKIP = "skip",
    MECO = "meco",
    STRK = "strk",
    HMHD = "hmhd",
    NMHD = "nmhd",
    IODS = "iods",
    XML = "xml ",
    BXML = "bxml",
    IPRO = "ipro",
    MERE = "mere",
    MOOV = "moov",
    TRAK = "trak",
    EDTS = "edts",
    MDIA = "mdia",
    MINF = "minf",
    SMHD = "smhd",
    DINF = "dinf",
    DREF = "dref",
    STBL = "stbl",
    MVEX = "mvex",
    MOOF = "moof",
    TRAF = "traf",
    VTTE = "vtte",
    VTTC = "vttc",
    PAYL = "payl",
    TREF = "tref",
    IREF = "iref",
    MFRA = "mfra",
    HNTI = "hnti",
    HINF = "hinf",
    STRD = "strd",
    SINF = "sinf",
    RINF = "rinf",
    SCHI = "schi",
    TRGR = "trgr",
    UDTA = "udta",
    IPRP = "iprp",
    IPCO = "ipco",
    UUID = "uuid",
    STTS = "stts",
    CTTS = "ctts",
    STSS = "stss",
    STSZ = "stsz",
    STZ2 = "stz2",
    STSC = "stsc",
    STCO = "stco",
    CO64 = "co64",
    MVHD = "mvhd",
    TKHD = "tkhd",
    MDHD = "mdhd",
    HDLR = "hdlr",
    FTYP = "ftyp",
    STSD = "stsd",
    AVC1 = "avc1",
    AVC3 = "avc3",
    AVCC = "avcC",
    HEV1 = "hev1",
    HVC1 = "hvc1",
    HVCC = "hvcC",
    VVC1 = "vvc1",
    VVI1 = "vvi1",
    VVCC = "vvcC",
    MP4A = "mp4a",
    MP4V = "mp4v",
    VP09 = "vp09",
    VPCC = "vpcC",
    AV01 = "av01",
    AV1C = "av1C",
    OPUS = "Opus",
    FLAC = "fLaC",
    ESDS = "esds",
    WAVE = "wave",
    DFLA = "dfLa",
    DOPS = "dOps",
    TREX = "trex",
    MFHD = "mfhd",
    TFHD = "tfhd",
    TFDT = "tfdt",
    TRUN = "trun",
    COLR = "colr",
    PASP = "pasp",
    BTRT = "btrt",
    TEXT = "text",
    VMHD = "vmhd",
    ELST = "elst",
    URL = "url ",
    NONE = "none",
    STPP = "stpp",
    WVTT = "wvtt",
    TX3G = "tx3g",
    C608 = "c608",
    MFRO = "mfro",
    TFRA = "tfra",
    MINF_HDLR = "minf_hdlr",
    FRMA = "frma",
    DAC3 = "dac3",
    DEC3 = "dec3",
    EC_3 = "ec-3",
    AC_3 = "ac-3"
}
export declare const BasicBoxs: BoxType[];
export declare const FullBoxs: BoxType[];
export declare const ContainerBoxs: BoxType[];
export declare const enum TFHDFlags {
    BASE_DATA_OFFSET = 1,
    SAMPLE_DESCRIPTION = 2,
    SAMPLE_DURATION = 8,
    SAMPLE_SIZE = 16,
    SAMPLE_FLAGS = 32,
    DURATION_EMPTY = 65536,
    DEFAULT_BASE_IS_MOOF = 131072
}
export declare const enum TRUNFlags {
    DATA_OFFSET = 1,
    FIRST_FLAG = 4,
    DURATION = 256,
    SIZE = 512,
    FLAGS = 1024,
    CTS_OFFSET = 2048
}
export declare const enum SampleFlags {
    DEGRADATION_PRIORITY_MASK = 65535,
    IS_NON_SYN = 65536,
    PADDING_MASK = 917504,
    REDUNDANCY_MASK = 3145728,
    DEPENDED_MASK = 12582912,
    DEPENDS_MASK = 50331648,
    DEPENDS_NO = 33554432,
    DEPENDS_YES = 16777216
}
export declare const enum MP4Tag {
    MP4_O_DESCR_TAG = 1,
    MP4_IO_DESCR_TAG = 2,
    MP4_ES_DESCR_TAG = 3,
    MP4_DEC_CONFIG_DESCR_TAG = 4,
    MP4_DEC_SPECIFIC_DESCR_TAG = 5,
    MP4_SL_DESCR_TAG = 6
}
export declare const enum TKHDFlags {
    ENABLED = 1,
    IN_MOVIE = 2,
    IN_PREVIEW = 4,
    POSTER = 8
}
