declare const support: {
    browser: import("../types/type").Browser;
    blob: boolean;
    wasm: boolean;
    fetch: boolean;
    webgl: boolean;
    worker: boolean;
    mse: boolean;
    arrayBuffer: boolean;
    audioContext: boolean;
    audioWorklet: boolean;
    videoDecoder: boolean;
    videoEncoder: boolean;
    audioDecoder: boolean;
    audioEncoder: boolean;
    atomics: boolean;
    shareArrayBuffer: boolean;
    thread: boolean;
    webgpu: boolean;
    offscreenCanvas: boolean;
    workerMSE: boolean;
    webAssemblyGlobal: boolean;
    jspi: boolean;
    proxy: boolean;
    simd: boolean;
    wasmBaseSupported: boolean;
};
export default support;
